version: '3.5'

services:
  postgres:
    container_name: microretro_pg_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: microretro
    volumes:
      - /tmp/postgres/retro:/data/postgres
    networks:
      - microretro
    restart: unless-stopped

  micro-retro:
    container_name: microretro
    image: noki/micro-retro:latest
    ports:
      - "4000:4000"
    depends_on:
      - "postgres"
    networks:
      - microretro
    restart: unless-stopped

networks:
  microretro:
    driver: bridge